apiVersion: v1
kind: ConfigMap
metadata:
  name: {cluster-metadb-config}
  namespace: {cluster_namespace}
data:
  my.cnf: |-
    [mysqld]
    port    = {cluster-metadb-listen-port}
    default-time-zone = '+8:00'
    character-set-server = utf8
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {cluster_metadb_host_name}
  namespace: {cluster_namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {cluster_metadb_host_name}
  template:
    metadata:
      labels:
        component: {cluster_metadb_host_name}
    spec:
      imagePullSecrets:
        - name: docker-registry-key
      hostname: {cluster_metadb_host_name}
      containers:
        - name: {cluster_metadb_host_name}
          image: {docker_img_srv_url}/mariadb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {cluster-metadb-listen-port}
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{mysql-root-pwd}"
          volumeMounts:
            - name: {cluster-metadb-config}
              mountPath: /etc/mysql/conf.d/
          livenessProbe:
            tcpSocket:
              port: {cluster-metadb-listen-port}
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: {cluster-metadb-config}
          configMap:
            name: {cluster-metadb-config}
---
apiVersion: v1
kind: Service
metadata:
  name: dn-{cluster_metadb_host_name}
  namespace: {cluster_namespace}
  labels:
    component: {cluster_metadb_host_name}
spec:
  ports:
  - port:  {cluster-metadb-listen-port}
    name: cluster-metadb
    protocol: TCP
  selector:
    component: {cluster_metadb_host_name}